name: 'Download llvmlite Conda Artifact'
description: 'Download llvmlite conda artifact from cross-repo workflow run'
inputs:
  llvmlite-run-id:
    description: 'llvmlite workflow run ID (optional)'
    required: false
    default: ''
  platform:
    description: 'Platform identifier (linux-64, osx-arm64, win-64, linux-aarch64)'
    required: true
  python-version:
    description: 'Python version (e.g., 3.10, 3.11)'
    required: true
runs:
  using: composite
  steps:
    - name: Download llvmlite Artifact
      if: ${{ inputs.llvmlite-run-id != '' }}
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        name: llvmlite-${{ inputs.platform }}-py${{ inputs.python-version }}
        path: llvmlite_conda
        run-id: ${{ inputs.llvmlite-run-id }}
        repository: numba/llvmlite
        github-token: ${{ secrets.GITHUB_TOKEN }}

