name: 'Build Conda Package'
description: 'Build Numba conda package'
inputs:
  platform:
    description: 'Platform identifier (linux-64, osx-arm64, win-64, linux-aarch64)'
    required: true
  python-version:
    description: 'Python version (e.g., 3.10, 3.11)'
    required: true
  numpy-build:
    description: 'NumPy version for build (e.g., 2.0)'
    required: true
  llvmlite-run-id:
    description: 'llvmlite workflow run ID (optional)'
    required: false
    default: ''
  conda-channel-numba:
    description: 'Conda channel for numba (default: numba/label/dev)'
    required: false
    default: 'numba/label/dev'
  extra-channels:
    description: 'Extra conda channels (space-separated, e.g., "-c channel1 -c channel2")'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Build Numba conda package
      shell: bash
      env:
        CONDA_CHANNEL_DIR: conda_channel_dir
      run: |
        mkdir -p $CONDA_CHANNEL_DIR

        # Set channel based on whether llvmlite artifact was downloaded
        if [ "${{ inputs.llvmlite-run-id }}" != "" ]; then
          if [ "${{ inputs.platform }}" = "win-64" ]; then
            LLVMLITE_CHANNEL="${{ github.workspace }}/llvmlite_conda"
          else
            LLVMLITE_CHANNEL="file://${{ github.workspace }}/llvmlite_conda"
          fi
        else
          LLVMLITE_CHANNEL="${{ inputs.conda-channel-numba }}"
        fi

        if [ -n "${{ inputs.extra-channels }}" ]; then
          extra_args=(${{ inputs.extra-channels }})
        else
          extra_args=()
        fi

        if [ "${{ inputs.platform }}" = "win-64" ]; then
          conda build --debug -c $LLVMLITE_CHANNEL "${extra_args[@]}" -c defaults \
            --python=${{ inputs.python-version }} \
            --numpy=${{ inputs.numpy-build }} \
            buildscripts/condarecipe.local/ \
            --output-folder=$CONDA_CHANNEL_DIR \
            --no-test
        else
          conda build --debug -c "${LLVMLITE_CHANNEL}" "${extra_args[@]}" -c defaults \
            --python=${{ inputs.python-version }} \
            --numpy=${{ inputs.numpy-build }} blas=*=openblas \
            buildscripts/condarecipe.local/ \
            --output-folder=$CONDA_CHANNEL_DIR \
            --no-test
        fi

