# Numba/llvmlite stack needs an older compiler for backwards compatibility.
c_compiler_version:         # [linux]
  - 7                       # [linux and (x86_64 or ppc64le)]
  - 11                      # [linux and aarch64]

cxx_compiler_version:       # [linux]
  - 7                       # [linux and (x86_64 or ppc64le)]
  - 11                      # [linux and aarch64]

fortran_compiler_version:   # [linux]
  - 7                       # [linux and (x86_64 or ppc64le)]
  - 11                      # [linux and aarch64]

numpy_build:
  - "2.0"                   # [py>=311 and py<313]
  - "2.1"                   # [py==313]
  - "1.26"                  # [py==310]
