name: 'Setup Conda Environment'
description: 'Setup Miniconda for conda builds'
inputs:
  python-version:
    description: 'Python version for conda (optional, defaults to 3.12)'
    required: false
    default: '3.12'
  platform:
    description: 'Platform identifier (linux-64, osx-arm64, win-64)'
    required: true
runs:
  using: composite
  steps:
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@835234971496cad1653abb28a638a281cf32541f # v3.2.0
      with:
        python-version: ${{ inputs.python-version != '' && inputs.python-version || '3.12' }}
        auto-update-conda: true
        auto-activate-base: true
        activate-environment: ${{ inputs.platform == 'win-64' && '' || true }}

