name: 'Install conda-build'
description: 'Install conda-build and dependencies'
inputs:
  platform:
    description: 'Platform identifier (linux-64, osx-arm64, win-64, linux-aarch64)'
    required: true
runs:
  using: composite
  steps:
    - name: Install conda-build
      shell: bash
      run: |
        if [ "${{ inputs.platform }}" = "win-64" ]; then
          conda install conda-build
        else
          conda install conda-build "conda-libmamba-solver<25.11"
        fi

