name: build-numba-whl-win64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_wheels:
    name: build_${{ matrix.platform }}_py${{ matrix.python }}_npy${{ matrix.numpy }}${{ matrix.tbb && '_tbb' || '' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows x64 (with TBB)
          - os: windows-latest
            platform: win_64
            python: '3.10'
            numpy: '2.0.0rc1'
            tbb: true
          - os: windows-latest
            platform: win_64
            python: '3.11'
            numpy: '2.0.0rc1'
            tbb: true
          - os: windows-latest
            platform: win_64
            python: '3.12'
            numpy: '2.0.0rc1'
            tbb: true

    defaults:
      run:
        shell: pwsh

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Miniconda
      shell: pwsh
      run: |
        $wc = New-Object net.webclient
        $wc.Downloadfile("https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe", "Miniconda3-latest-Windows-x86_64.exe")
        Start-Process "Miniconda3-latest-Windows-x86_64.exe" "/S /D=C:\Miniconda3" -Wait
        echo "C:\Miniconda3\Scripts" >> $env:GITHUB_PATH
        echo "C:\Miniconda3\Library\bin" >> $env:GITHUB_PATH

    - name: Configure Conda
      run: |
        conda config --set always_yes yes
        conda config --add channels conda-forge
        conda config --add channels numba
        conda info
        conda list

    - name: Create Build Environment
      run: |
        conda create -n build_env `
          python=${{ matrix.python }} `
          numpy=${{ matrix.numpy }} `
          -c numba `
          -c ad-testing/label/numpy2
        conda activate build_env
        if (${{ matrix.tbb }}) {
          python -m pip install tbb==2021.6 tbb-devel==2021.6
        }
        python -m pip install --upgrade wheel
        conda list

    - name: Build Wheel
      run: |
        # Initialize conda for the shell
        $Env:CONDA_EXE = "C:\Miniconda3\Scripts\conda.exe"
        $Env:_CE_M = ""
        $Env:_CE_CONDA = ""
        $Env:_CONDA_ROOT = "C:\Miniconda3"
        $Env:_CONDA_EXE = "C:\Miniconda3\Scripts\conda.exe"
        (& "C:\Miniconda3\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | Invoke-Expression
        conda activate build_env
        # Show Python version to verify correct version
        python --version
        python setup.py -q bdist_wheel
        Get-ChildItem dist

    - name: Create Test Environment
      run: |
        # Initialize conda for the shell
        $Env:CONDA_EXE = "C:\Miniconda3\Scripts\conda.exe"
        $Env:_CE_M = ""
        $Env:_CE_CONDA = ""
        $Env:_CONDA_ROOT = "C:\Miniconda3"
        $Env:_CONDA_EXE = "C:\Miniconda3\Scripts\conda.exe"
        (& "C:\Miniconda3\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | Invoke-Expression
        # Create and activate test environment
        conda create -n test_env python=${{ matrix.python }} numpy=${{ matrix.numpy }} "wheel>=0.32" twine -y
        conda activate test_env
        conda list

    - name: Test Wheel
      run: |
        # Initialize conda for the shell
        $Env:CONDA_EXE = "C:\Miniconda3\Scripts\conda.exe"
        $Env:_CE_M = ""
        $Env:_CE_CONDA = ""
        $Env:_CONDA_ROOT = "C:\Miniconda3"
        $Env:_CONDA_EXE = "C:\Miniconda3\Scripts\conda.exe"
        (& "C:\Miniconda3\Scripts\conda.exe" "shell.powershell" "hook") | Out-String | Invoke-Expression
        conda activate test_env
        cd dist
        python -m pip install --extra-index https://pypi.anaconda.org/numba/label/wheels/simple (Get-Item *.whl).Name
        python -m pip list
        numba -s

    - name: Upload Wheel Artifact
      uses: actions/upload-artifact@v3
      with:
        name: numba-${{ matrix.platform }}-py${{ matrix.python }}-npy${{ matrix.numpy }}${{ matrix.tbb && '-tbb' || '' }}
        path: dist/*.whl